# Site settings
author: Karl Van Burkleo
title: Keystrokes
header-img: img/home-bg.png
email: karl.vanburkleo@gmail.com
copyright_name: Karl Van Burkleo
description: > # this means to ignore newlines until "baseurl:"
  A look into my journey to becoming a data scientist. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AudioElevators

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
